rps: "1"
frontendAddr:
redisAddr:
matchTimeout: "10s"
connectTimeout: "3s"
replicas: 1
image:
podAnnotations: {}
podLabels: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
podMonitor:
  enabled: true
