{
 "title": "Minimatch Loadtest",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "attacker Ticket Assigned Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(minimatch_attacker_match_assigned_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(minimatch_attacker_match_assigned_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(minimatch_attacker_match_assigned_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "attacker Tickets Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(minimatch_attacker_match_finished_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "minimatch Backend Fetch tickets Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(minimatch_backend_fetch_tickets_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(minimatch_backend_fetch_tickets_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(minimatch_backend_fetch_tickets_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "minimatch Backend Assign to redis latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(minimatch_backend_assign_to_redis_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(minimatch_backend_assign_to_redis_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(minimatch_backend_assign_to_redis_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "minimatch Match Function Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(minimatch_backend_match_function_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(minimatch_backend_match_function_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(minimatch_backend_match_function_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "minimatch Backend Assigner Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(minimatch_backend_assigner_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(minimatch_backend_assigner_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(minimatch_backend_assigner_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "minimatch Backend Tickets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(minimatch_backend_tickets_fetched_total[$__rate_interval]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(minimatch_backend_tickets_assigned_total[$__rate_interval]))",
     "legendFormat": "Assigned"
    }
   ]
  },
  {
   "title": "Overlapping Matches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(minimatch_loadtest_overlapping_tickets_within_backend_total[$__rate_interval]))",
     "legendFormat": "Overlapping within backend"
    },
    {
     "expr": "sum(rate(minimatch_loadtest_overlapping_tickets_inter_backends_total[$__rate_interval]))",
     "legendFormat": "Overlapping inter backends"
    }
   ]
  }
 ]
}