frontend:
  service:
    type: ClusterIP
  deployment:
    replicas: 1
    image:
    env: {}
    resources: {}
backend:
  tickRate: "1s"
  deployment:
    replicas: 1
    image:
    env: {}
    resources: {}
podMonitor:
  enabled: false
