apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minimatch.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minimatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "minimatch.commonSelectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "minimatch.commonSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: {{ .Values.frontend.deployment.image }}
          env:
            {{- range .Values.frontend.deployment.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.frontend.deployment.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 50504
              protocol: TCP
            - name: metrics
              containerPort: 2112
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minimatch.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minimatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 50504
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "minimatch.commonSelectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
