repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: ~51.2.0
    namespace: monitoring
    createNamespace: true
    wait: true
    values:
    - prometheus:
        prometheusSpec:
          serviceMonitorNamespaceSelector: {}
          serviceMonitorSelectorNilUsesHelmValues: false
          podMonitorNamespaceSelector: {}
          podMonitorSelectorNilUsesHelmValues: false
      grafana:
        sidecar:
          dashboards:
            enabled: true
        adminPassword: test
      coreDns:
        enabled: false
      kubeControllerManager:
        enabled: false
      kubeEtcd:
        enabled: false
      kubeProxy:
        enabled: false
      kubeScheduler:
        enabled: false
      nodeExporter:
        enabled: false